# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            nathan devrio
description:      "ph.d. student in human-computer interaction"
url:              http://nriopelle.me
baseurl:          /

github:
  repo:           https://github.com/riopelln/riopellnpersonalsite
