# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        none
relative_permalinks: false

# Setup
title:            Nathan DeVrio
description:      "ph.d. student in human-computer interaction"
url:              https://www.ndevrio.com

github:
  repo:           https://github.com/riopelln/ndevriopersonalsite
