# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            nathan devrio
description:      "ph.d. student in human-computer interaction"
url:              http://ndevrio.com
baseurl:          /

github:
  repo:           https://github.com/riopelln/ndevriopersonalsite
