# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            nathan riopelle
description:      'undergraduate senior in computer engineering'
url:              http://nriopelle.me
baseurl:          /

github:
  repo:           https://github.com/riopelln/riopellnpersonalsite
